/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.xxl.job.admin;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.runtime.SmartAssertions.*;
import com.xxl.job.admin.XxlJobAdminApplication;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class XxlJobAdminApplication_SSTest extends XxlJobAdminApplication_SSTest_scaffolding {
// allCoveredLines:[10, 13]

  @Test(timeout = 4000)
  public void test_main_0()  throws Throwable  {
      //caseID:a0e01aa92a1ee04e4fcd8ff2262a347e
      //CoveredLines: [10, 13]
      //Input_0_String[]: stringArray0
      
      XxlJobAdminApplication xxlJobAdminApplication0 = new XxlJobAdminApplication();
      String[] stringArray0 = new String[0];
      
      //Call method: main
      // Undeclared exception!
      try { 
        XxlJobAdminApplication.main(stringArray0);
      } catch(Throwable e) {
         verifyException("org.springframework.core.io.support.SpringFactoriesLoader", e);
         assertEquals("org.smartunit.runtime.mock.java.lang.MockIllegalArgumentException", e.getClass().getName());
         assertEquals("Unable to instantiate factory class [org.springframework.boot.logging.log4j2.Log4J2LoggingSystem.Factory] for factory type [org.springframework.boot.logging.LoggingSystemFactory]", e.getMessage());
      }
  }
}
