/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.xxl.job.executor.sample.frameless.jobhandler;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.xxl.job.executor.sample.frameless.jobhandler.SampleXxlJob;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class SampleXxlJob_SSTest extends SampleXxlJob_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_init_0()  throws Throwable  {
      //caseID:4bc8c0447dba2d3a755f87056f9da055
      SampleXxlJob sampleXxlJob0 = new SampleXxlJob();

      //invoke method for sampleXxlJob0
      sampleXxlJob0.init();
  }
  @Test(timeout = 4000)
  public void test_demoJobHandler2_1()  throws Throwable  {
      //caseID:1b740d8d46ff5b435222d9121a32d439
      SampleXxlJob sampleXxlJob0 = new SampleXxlJob();

      //invoke method for sampleXxlJob0
      sampleXxlJob0.demoJobHandler2();
  }
  @Test(timeout = 4000)
  public void test_destroy_2()  throws Throwable  {
      //caseID:10c49acb7b14b8e27b92a8e359e74f74
      SampleXxlJob sampleXxlJob0 = new SampleXxlJob();

      //invoke method for sampleXxlJob0
      sampleXxlJob0.destroy();
  }
  @Test(timeout = 4000)
  public void test_shardingJobHandler_3()  throws Throwable  {
      //caseID:726ba6d6beb08853599b38eec1a1ba50
      SampleXxlJob sampleXxlJob0 = new SampleXxlJob();

      //invoke method for sampleXxlJob0
      sampleXxlJob0.shardingJobHandler();
  }
  @Test(timeout = 4000)
  public void test_httpJobHandler_4()  throws Throwable  {
      //caseID:f18cb85a386565e4ab3ef5b300ae51cd
      SampleXxlJob sampleXxlJob0 = new SampleXxlJob();

      //invoke method for sampleXxlJob0
      sampleXxlJob0.httpJobHandler();
  }
  @Test(timeout = 4000)
  public void test_commandJobHandler_5()  throws Throwable  {
      //caseID:78785c76bbba8850563418cffb84eb33
      SampleXxlJob sampleXxlJob0 = new SampleXxlJob();

      //invoke method for sampleXxlJob0
      sampleXxlJob0.commandJobHandler();
  }}
