/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.xxl.job.executor.sample.frameless.jobhandler;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.xxl.job.executor.sample.frameless.jobhandler.SampleXxlJob;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class SampleXxlJob_SSTest extends SampleXxlJob_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_init_0()  throws Throwable  {
      //caseID:958f2fb7a8f086c70d472e396d9c985c
      SampleXxlJob sampleXxlJob0 = new SampleXxlJob();

      //invoke method for sampleXxlJob0
      sampleXxlJob0.init();
  }
  @Test(timeout = 4000)
  public void test_destroy_1()  throws Throwable  {
      //caseID:f566b24f6fd2c1431edc8953fb015823
      SampleXxlJob sampleXxlJob0 = new SampleXxlJob();

      //invoke method for sampleXxlJob0
      sampleXxlJob0.destroy();
  }
  @Test(timeout = 4000)
  public void test_demoJobHandler2_2()  throws Throwable  {
      //caseID:30a074d77b146dd68f082003a5bc66ca
      SampleXxlJob sampleXxlJob0 = new SampleXxlJob();

      //invoke method for sampleXxlJob0
      sampleXxlJob0.demoJobHandler2();
  }
  @Test(timeout = 4000)
  public void test_httpJobHandler_3()  throws Throwable  {
      //caseID:01d62cb221b7bbb1f2d0f73a557dc8e3
      SampleXxlJob sampleXxlJob0 = new SampleXxlJob();

      //invoke method for sampleXxlJob0
      sampleXxlJob0.httpJobHandler();
  }
  @Test(timeout = 4000)
  public void test_shardingJobHandler_4()  throws Throwable  {
      //caseID:3f0765c987ac3d2874531e35216d10b1
      SampleXxlJob sampleXxlJob0 = new SampleXxlJob();

      //invoke method for sampleXxlJob0
      sampleXxlJob0.shardingJobHandler();
  }
  @Test(timeout = 4000)
  public void test_commandJobHandler_5()  throws Throwable  {
      //caseID:8e07b2816eb3a7a971cd15d3550155e9
      SampleXxlJob sampleXxlJob0 = new SampleXxlJob();

      //invoke method for sampleXxlJob0
      sampleXxlJob0.commandJobHandler();
  }}
