/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.xxl.job.executor.sample.frameless;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class FramelessApplication_SSTest extends FramelessApplication_SSTest_scaffolding {
  @Test
  public void notGeneratedAnyTest() {
    // SmartUnit did not generate any tests
  }
}
