/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.xxl.job.executor.sample.frameless.config;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import static org.smartunit.runtime.SmartAssertions.*;
import com.xxl.job.core.executor.impl.XxlJobSimpleExecutor;
import com.xxl.job.executor.sample.frameless.config.FrameLessXxlJobConfig;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class FrameLessXxlJobConfig_SSTest extends FrameLessXxlJobConfig_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_loadProperties_0()  throws Throwable  {
      //caseID:8f73d42233b741c0f6200f9042d63d05
      FrameLessXxlJobConfig frameLessXxlJobConfig0 = new FrameLessXxlJobConfig();
      // Undeclared exception!
      try { 
        FrameLessXxlJobConfig.loadProperties("xxl-job, JobThread-");
      } catch(Throwable e) {
         verifyException("java.io.Reader", e);
         assertEquals("java.lang.NullPointerException", e.getClass().getName());
      }
  }
  @Test(timeout = 4000)
  public void test_getInstance_1()  throws Throwable  {
      //caseID:fc3bcd03b48a8a52204cd65a2c917fd2
      FrameLessXxlJobConfig frameLessXxlJobConfig0 = FrameLessXxlJobConfig.getInstance();

      //invoke method for frameLessXxlJobConfig0
      assertNotNull(frameLessXxlJobConfig0);
  }
  @Test(timeout = 4000)
  public void test_destroyXxlJobExecutor_2()  throws Throwable  {
      //caseID:760537380b0aea25348bdac0215897fe
      FrameLessXxlJobConfig frameLessXxlJobConfig0 = new FrameLessXxlJobConfig();
      XxlJobSimpleExecutor xxlJobSimpleExecutor0 = mock(XxlJobSimpleExecutor.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());

      //invoke method for frameLessXxlJobConfig0
      PrivateAccess.setVariable((Class<?>) FrameLessXxlJobConfig.class, frameLessXxlJobConfig0, "xxlJobExecutor", (Object) xxlJobSimpleExecutor0);

      //invoke method for frameLessXxlJobConfig0
      frameLessXxlJobConfig0.destroyXxlJobExecutor();
  }
  @Test(timeout = 4000)
  public void test_initXxlJobExecutor_3()  throws Throwable  {
      //caseID:89404139a2967ef04bff8c1b4b56caa9
      FrameLessXxlJobConfig frameLessXxlJobConfig0 = new FrameLessXxlJobConfig();

      //invoke method for frameLessXxlJobConfig0
      frameLessXxlJobConfig0.initXxlJobExecutor();
  }}
